services: 
    frontend:
      build: ./React-Frontend
      networks: 
        - front_back
      ports:
       - 8080:80
      depends_on:
        - backend

    backend: 
      build: ./DotNet-Backend
      networks:
        - front_back
        - db_back
      environment:
        - DB_HOST=${DB_HOST}
        - DB_PORT=${DB_PORT}
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD_FILE=/run/secrets/db_password
      secrets:
        - db_password
      depends_on:
        - db

    db:
      image: mysql:8.0
      volumes:
        - db-data:/var/lib/mysql
      networks:
        - db_back
      secrets:
        - db_password
      environment:
       - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_password
       - MYSQL_DATABASE=${DB_NAME}

volumes:
  db-data:

networks:
  front_back:
  db_back:

secrets:
  db_password:
    file: ./db_password.txt