- name : main playbook
  hosts : localhost
  gather_facts: yes
  become: yes
  vars:
    username: "{{lookup('env', 'username')}}"
    password: "{{lookup('env', 'password')}}"
    MYSQL_ROOT_PASSWORD: "{{lookup('env', 'MYSQL_ROOT_PASSWORD')}}"
  tasks:
    - name: check if docker is installed
      ignore_errors: true
      ansible.builtin.package:
        name: 
          - docker-ce
          - docker-compose-plugin
        state: present

    - name: ensure docker service is running
      ansible.builtin.service:
         name: docker 
         state: started
         enabled: yes 

    - name: dockerhub login
      ansible.builtin.shell: |
        echo "{{password}}" | docker login ghcr.io -u "{{username}}" --password-stdin
      changed_when: false

    # - name: Create db_password.txt with variable content
    #   ansible.builtin.copy:
    #     dest: ./db_password.txt
    #     content: "{{ MYSQL_ROOT_PASSWORD }}"

    - name: run docker compose 
      ansible.builtin.shell: |
         docker compose up -d
      args:
         chdir: "{{playbook_dir}}"
      environment: 
           DB_HOST: "{{lookup('env', 'DB_HOST')}}"
           DB_PORT: "{{lookup('env', 'DB_PORT')}}"
           DB_NAME: "{{lookup('env', 'DB_NAME')}}"
           DB_USER: "{{lookup('env', 'DB_USER')}}"
           APP_URL: "{{lookup('env', 'APP_URL')}}"
           MYSQL_ROOT_PASSWORD: "{{lookup('env', 'MYSQL_ROOT_PASSWORD')}}"

    # - name: removing the password file
    #   ansible.builtin.file:
    #     path: ./db_password.txt
    #     state: absent